name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with black and pylint
      run: |
        pip install black pylint
        black --check .
        pylint app.py

    - name: Run unit tests
      run: |
        pytest --cov-report term-missing --cov=app tests/
